### ISSUE TITLE
Double checking my releases naming understanding

### ISSUE THREAD

**Issue by zappacor** [marcosfad/mbp-ubuntu-kernel#8]
Is this, my releases naming understanding, correct:
1) for releases 5.8.X: version "mbp" includes all patches and "mbp-alt" doesn't
2) for releases 5.7.X: version "mbp-alt" includes all patches and "mbp" doesn't

**Comment by networkException** [comment]
My understanding was that -alt always contained one more patch that might fix or break a black screen issue. I might be wrong tho. What I definitely know however is that 5.8.x is quite unstable and not recommended to be used. That would leave 5.7.19 as the best option right now.

**Comment by marcosfad** [comment]
Hi. Yes that all of the above is correct.
* The 5.8-mbp and 5.7-mbp-alt have all patches: This is due to, at the beginning, the patch 2001 was producing a blank screen on my mbp16,1. But Aunali1 was able to fix this issue later on. I keep releasing the alternative version, just because some community members said they have better results. I'm no longer using it though.
* 5.8 is unstable on mac book Pro

Aunali1 also proposed to rename the kernel to t2. Something that may be more appropriated, but this hasn't been implemented yet.

**Comment by zappacor** [comment]
Tons of thanks Marcos!
